version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.3.0
  - dependency-name: webpack
    versions:
    - 4.44.2
